LOCAL_PATH := device/sony/g3212


ANDROID_COMPILE_WITH_JACK := true
SELINUX_IGNORE_NEVERALLOWS := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_PHONY_TARGETS := true
BUILD_BROKEN_ENG_DEBUG_TAGS := true
BUILD_BROKEN_ANDROIDMK_EXPORTS := true
DISABLE_APEX_LIBS_ABSENCE_CHECK := true
ALLOW_MISSING_DEPENDENCIES := true
#WITHOUT_CHECK_API := true

include $(LOCAL_PATH)/platform/board.mk

# Platform
#ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_BOARD_PLATFORM := mt6757
TARGET_NO_BOOTLOADER := true

# CPU
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := cortex-a53
#TARGET_CPU_SMP := true

TARGET_2ND_ARCH := arm
ifeq ($(BUILD_ONLY_TWRP),true)
	# android upto oreo 8.1.0 uses "armv7-a-neon"
	TARGET_2ND_ARCH_VARIANT := armv7-a-neon
else
	ifeq ($(BUILD_OREO),true)
		TARGET_2ND_ARCH_VARIANT := armv7-a-neon
	else
		# if you use "armv8-a" on oreo 8.1.0, error will eat your cat
		TARGET_2ND_ARCH_VARIANT := armv8-a
	endif
endif
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a53
TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true
TARGET_CPU_CORTEX_A53 := true
TARGET_BOOTLOADER_BOARD_NAME := $(TARGET_BOARD_PLATFORM)

# Kernel
TARGET_USES_64_BIT_BINDER := true
TARGET_IS_64_BIT := true
#LZMA_RAMDISK_TARGETS := boot,recovery
BOARD_KERNEL_BASE := 0x40078000
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x04f88000 --tags_offset 0x03f88000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_CMDLINE := androidboot.selinux=permissive bootopt=64S3,32N2,64N2
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
TARGET_KERNEL_SOURCE := kernel/sony/mt6757
KERNEL_DIR := $(TARGET_KERNEL_SOURCE)
TARGET_KERNEL_CONFIG := redwood_defconfig

# Manifest
DEVICE_MANIFEST_FILE := $(LOCAL_PATH)/configs/manifest.xml
DEVICE_MATRIX_FILE   := $(LOCAL_PATH)/configs/compatibility_matrix.xml

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 50135040
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_PARTITION_SIZE := 209715200
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 5788139520
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_PARTITION_SIZE := 24536678400
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true

# Include needed symbols
TARGET_INCLUDE_LIBPRELOAD := true

# Display
DEVICE_RESOLUTION := 1080x1920
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 1920

# Bluetooth
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(LOCAL_PATH)/bluetooth

# LightHAL
TARGET_PROVIDES_LIBLIGHT := true

# Recovery
TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/rootdir/fstab.mt6757

ifeq ($(BUILD_ONLY_TWRP),true)
	# TWRP
	BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_23x41.h\"
	TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
	TW_DEVICE_VERSION := DANiO
	RECOVERY_SDCARD_ON_DATA := true
	TW_INCLUDE_CRYPTO := true
	TW_USE_TOOLBOX := true
	TWRP_INCLUDE_LOGCAT := true
	TW_MAX_BRIGHTNESS := 255
	TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone1/temp
	TWHAVE_SELINUX := true
	# Crypto
	TW_CRYPTO_REAL_BLKDEV := "/dev/block/platform/mtk-msdc.0/11230000.msdc0/by-name/userdata" 
	TW_CRYPTO_MNT_POINT := "/data"
	TW_CRYPTO_KEY_LOC := "footer"
	TW_CRYPTO_FS_OPTIONS := "nosuid,nodev,noatime,discard,noauto_da_alloc,data=ordered"
	TW_INCLUDE_L_CRYPTO := true
endif

TARGET_SYSTEM_PROP := $(LOCAL_PATH)/system.prop

# SELinux
ifneq ($(BUILD_ONLY_TWRP),true)
	BOARD_SEPOLICY_VERS := 27.0
	BOARD_SEPOLICY_DIRS += $(LOCAL_PATH)/sepolicy
endif
